*KEYWORD
*DEFINE_BOX_TITLE
AAccel. Rohbau Klebeflaechen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000100 1258.3196 1264.3390 -334.8600  335.1439   51.0000   51.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VOWA_VARIANTEN_AllCATPart_Halter_hinten_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000110  707.5000  795.5000  126.4178  234.0236   19.0000   62.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_LT_KOFF_UT
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000116  364.8364  416.9478  336.4601  434.4673   26.0000  101.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_VERBINDUNGSELEMENT_VERTIKALTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000118  727.5000  788.5000  245.0000  335.0000  489.1323  561.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_ANBINDUNG_KUEHLERKONSOLE_UNTEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000130  454.8921  614.4829  371.9769  468.7226   26.0000   35.4500
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_KUEHLERHALTER_OBEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000131  490.7243  585.5314  393.0000  519.7299  344.1763  500.5424
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_KUEHLERHALTER_OBEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000133  490.7243  585.5314 -519.7299 -393.0000  344.1763  500.6690
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_TRAEGER_1_VO_PLATTE
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000150  359.4086  428.9982  326.2526  457.1316  228.0000  414.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AAccel. Rohbau
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000200 1258.3196 1264.3390 -334.8600  335.1439   51.0000   58.4931
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_VERSTREBUNG_KOFFERRAUM_HALTER_MITTE
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000300  330.5000  330.5000 -114.8984  114.5486   23.3928   58.3894
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_aussen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000430 1229.6273 1380.2269 -413.0249 -318.0000   48.5000   48.8660
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_aussen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000450 1230.5161 1378.1831 -435.5242 -371.7527   48.0018   65.2206
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_VERSTREBUNG_KOFFERRAUM_HALTER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000500  707.5000  740.0000  -95.5958   95.5961   -7.4999   62.0002
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_aussen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000530 1229.6273 1380.2269  318.0000  413.0249   48.5000   48.8660
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_aussen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000550 1230.5161 1378.1831  371.7527  435.5242   48.0018   65.2206
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VOWA_VARIANTEN_AllCATPart_Halter_hinten_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20000800  707.5000  795.5000 -234.0236 -126.4178   19.0000   62.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VOWA_VARIANTEN_AllCATPart_Rigid
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001000 1215.0000 1682.0000 -868.4973  868.4973   -5.2000  658.9821
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_VARIANTEN_AllCATPart_Abschlussteil_vorne_oben
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001100  303.9999  425.9081 -469.5727  469.5727  179.4665  487.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_Strebe_unten_seitlich
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001200  331.4474  707.5000 -307.7015 -150.2030   32.6968   50.8727
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSVERBINDUNG__LAENGSTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001300  676.9584  845.4448 -412.0014 -252.0000    0.0000  151.9024
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_LT_KOFF_UT
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001400  377.4907  728.0000 -408.5127 -359.9750   31.8867   95.1157
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_LT_KOFF_UT
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001500  364.8364  416.9478 -434.4673 -336.4601   26.0000  101.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_VERTIKALTRAEGER_OB
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001600  738.8948  772.0640 -319.0129 -159.5127  369.4997  512.5785
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_VERBINDUNGSELEMENT_VERTIKALTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001700  727.5000  788.5000 -335.0000 -245.0000  489.1323  561.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_RINGQUERTRAEGER_AUSSEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001800  735.4230  945.2682 -346.1983 -246.6951  272.3042  369.5964
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_Rohr_aussen_hinten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20001900  792.2613  965.7518 -394.0002 -370.9947  102.0066  254.6693
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_TRAEGER_1_VO_AUSSEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002000  343.6865 1215.0000 -439.0000 -351.0000  243.7292  398.3175
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSVERBINDUNG__LAENGSTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002100  788.7499  788.7505 -397.5000 -367.5000   98.5000  130.4820
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSVERBINDUNG__LAENGSTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002200  676.9999  801.4094 -368.3144 -341.7153   -4.9995   98.5115
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_ANBINDUNG_KUEHLERKONSOLE_UNTEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002300  454.8921  614.4829 -468.7226 -371.9769   26.0000   35.4500
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_LT_LI_OB
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002400 1179.6659 1274.3091 -693.4184 -608.0897  606.3759  648.6040
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_LT_RE_OB
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002500 1179.6659 1280.2389  608.0897  695.1267  606.3759  648.8604
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_LT_LI_OB_VORNE
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002600  381.5036 1012.3643 -616.3756 -375.2625  418.3357  636.9766
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_LT_RE_OB_VORNE
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002700  381.1692 1012.3643  374.6335  616.3584  418.4646  636.9766
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VARIANTE_1_TRAEGER_1_VO_PLATTE
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002800  359.4086  428.9982 -457.1316 -326.2526  228.0000  414.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_Quertraeger_Schottwand_ob
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20002900  729.9600  786.0000 -484.3555  484.3575  519.7579  568.1020
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AGussanbindung_Laengstr_Schottwand_ob
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003000  682.3552  819.7680  426.7220  552.9036  505.1370  579.6018
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AGussanbindung_Laengstr_Schottwand_ob
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003100  682.3552  819.7680 -552.9036 -426.7220  505.1370  579.6018
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VOWA_VARIANTEN_AllCATPart_Abschlussteil_vorne_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003200  329.3336  357.9284 -326.6637 -230.6591   26.9506   58.5005
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VOWA_VARIANTEN_AllCATPart_Abschlussteil_vorne_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003300  329.3336  357.9284  230.6591  326.6637   26.9506   58.5005
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_VARIANTEN_AllCATPart_Rohr_seitlich_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003400  740.0000  770.0000  156.5000  203.5000   62.5000  272.5137
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_VARIANTEN_AllCATPart_Strebe_unten_seitlich
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003500  331.4474  707.5000  150.2030  307.7015   32.6968   50.8727
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSVERBINDUNG__LAENGSTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003600  676.9584  845.4448  252.0000  412.0014    0.0000  151.9024
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_LT_KOFF_UT
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003700  377.4907  728.0000  359.9750  408.5127   31.8867   95.1157
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_VERTIKALTRAEGER_OB
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003800  738.8948  772.0640  159.5127  319.0129  369.4997  512.5785
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_RINGQUERTRAEGER_AUSSEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20003900  735.4230  945.2682  246.6951  346.1983  272.3042  369.5964
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_Rohr_aussen_hinten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004000  792.2613  965.7518  370.9947  394.0002  102.0066  254.6693
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_TRAEGER_1_VO_AUSSEN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004100  343.6865 1215.0000  351.0000  439.0000  243.6352  398.3175
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSVERBINDUNG__LAENGSTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004200  788.7499  788.7505  367.5000  397.5000   98.5000  130.4820
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSVERBINDUNG__LAENGSTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004300  676.9999  801.4094  341.7153  368.3144   -4.9995   98.5115
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_Abschlussteil_vorne_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004400  303.9996  425.9739 -469.6960  469.6960   22.3496  214.0004
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_innen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004500  823.0072 1279.7200 -670.4446 -313.9263   50.9999  646.3338
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_innen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004600  859.6384 1208.6343 -679.6724 -374.1319  223.3679  648.0992
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_innen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004700  823.0072 1279.7200  313.9263  670.4446   50.9999  646.3338
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_innen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004800  859.6384 1208.6343  374.1319  679.6724  223.3679  648.0992
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_VERSTREBUNG_KOFFERRAUM
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20004900  330.5000  707.5002  -49.0010   49.0010   28.8499   53.3504
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_aussen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20005000  823.0432 1279.6117 -485.3642 -318.0000   48.0018  536.3525
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_GUSSAUFNAHME_TR_1_STI_Traeger1_hinten_aussen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20005100  823.0432 1279.6117  318.0000  485.3642   48.0018  536.3525
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_Rohr_mitte_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20005200  711.0000  792.0001 -338.0005  338.0005   -4.0028   59.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_RINGQUERTRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20005300  734.9993  775.0012 -290.0909  290.0909  272.4579  369.5725
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APAR_MBG_VOWA_Rohr_seitlich_unten
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  20005400  740.0000  770.0000 -203.5000 -156.5000   62.5000  272.5137
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASchrauben_ Blocklaenge_Kontakt      (>ODB.KONTAKT1:9,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  22012051 1140.6196 1149.2186 -299.5927  299.5903   11.5000   21.5468
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.504.433.01-TM1________000_      (>SB_HX260LAD+Z_MDB:24SR_00,  >SH
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  22255312 1115.0000 1277.8326 -324.9769  324.9769    0.2234   12.1000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.504.437.01-TM1_000_HILFSRA      (>SB_HX260LAD+Z_MDB:24SR_00,  >SH
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  22255725 1116.3336 1276.4360 -323.6795 -199.1819    5.5500   19.8619
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.504.437.01-TM1_000_HILFSRA      (>SB_HX260LAD+Z_MDB:24SR_00,  >SH
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  22255825 1116.3336 1276.7804  199.1819  323.6795    5.5500   19.8619
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ANullschalen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000001  342.8711  422.4854 -463.0867  463.0867  222.4151  415.1350
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.02_DECKBLECH-T__001_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000002  129.5607  215.5393 -460.4290   -2.7783  268.0000  396.2626
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.02_DECKBLECH-T__001_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000003  129.5607  215.5393   -2.9428  460.4290  267.5791  396.2626
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000004  132.7686  239.6169 -455.0555    0.0105  277.4642  364.5719
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000005  132.8686  239.6169   -0.0001  455.0555  277.4668  364.5719
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_VERSTAERKUN__012_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000006  151.6089  198.0000 -269.7340    0.0000  273.9499  368.0499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_VERSTAERKUN__012_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000007  151.6089  198.0000   -0.0000  269.7336  273.9499  368.0499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000008  204.0841  352.7950 -392.0734 -357.9557  316.0000  371.3000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000010  208.2729  351.0381 -388.9946 -355.1560  270.7000  326.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000014  132.7295  208.5702 -455.2355    0.0105  271.9801  370.9551
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000015  132.7295  208.5702    0.0000  455.2355  271.9801  370.4655
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000108  204.0841  352.7950  357.9557  392.0734  316.0000  371.3000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000110  208.2729  351.0381  355.1560  388.9946  270.7000  326.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88000300  167.1530  220.1217  299.1518  358.8547  289.6239  347.1461
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88001008  207.9862  373.7401 -431.4560 -391.7583  316.0000  371.3000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88001010  208.6481  372.2570 -428.6555 -388.6688  270.7000  326.0094
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88001108  207.9862  373.7401  391.7583  431.4560  316.0000  371.3000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88001110  208.6481  372.2570  388.6688  428.6555  270.7000  326.0094
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AVE_992_VOWA_VARIANTE_1_AllCATPart____________@SKIN
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88001201  332.9206  402.5102 -471.2155  471.2155  218.0000  424.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88002010  336.9234  379.8601 -432.2253 -351.4730  269.7939  317.4526
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88002088  214.1138  381.2915 -434.9172 -353.5894  285.7055  372.0501
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88002110  336.9234  379.8601  351.4730  432.2253  269.7939  317.4526
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88002188  214.1138  381.2915  353.5894  434.9172  285.7055  372.0501
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010004  144.3076  195.7185 -288.3394    0.0000  277.4999  364.5046
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010005  143.9300  195.6138   -0.0001  288.3394  277.4999  364.5046
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_VERSTAERKUN__012_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010006  151.4010  198.0000 -280.0090    0.0000  273.9499  368.0499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_VERSTAERKUN__012_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010007  151.4010  198.0000   -0.0000  280.0091  273.9499  368.0499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010008  195.8425  357.4700 -393.2040 -357.9529  316.0000  367.6907
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010010  194.2413  356.6928 -388.7000 -355.1560  274.1981  326.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_QUERTRAEGER__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010014  207.6412  233.9387 -428.2011  428.2011  279.9621  362.0398
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010108  195.8425  357.4700  357.9529  393.2040  316.0000  367.6907
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88010110  194.2413  356.6928  355.1560  388.7000  274.1981  326.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88011008  199.6035  379.3948 -431.4560 -390.0521  315.9964  367.8836
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88011010  197.4599  377.9127 -428.6695 -387.8655  274.2000  326.0142
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88011108  199.6035  379.3948  390.0521  431.4560  315.9964  367.8836
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.521.00_CRASHBOX_OB__009_0_Z_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88011110  197.4599  377.9127  387.8655  428.6695  274.2000  326.0142
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ATH-Klebeflaechen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88099991  166.0214  171.9972   -3.0560    2.9451  273.9499  273.9499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASensor_elemente
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88099992  165.9892  171.9972   -3.0560    3.0287  268.9499  273.9499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ANullschalen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100001  328.0953  400.1036 -421.0370  421.0370   26.3988  136.2169
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_QUERTRAEGER002___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100100  113.9999  166.1299 -430.2887    0.0004   68.2287   97.1694
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_QUERTRAEGER002___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100101  113.9999  166.1299 -430.2887    0.0004   68.2287   97.1693
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_QUERTRAEGER002___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100102  113.9999  166.1188   -0.0049  430.2889   68.2275   97.1694
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_QUERTRAEGER002___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100103  113.9999  166.1188   -0.0049  430.2889   68.2275   97.1693
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_CRASHBOX_UN003___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100104  150.7948  364.5505 -424.7800 -351.0650   33.9409  105.8839
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_CRASHBOX_UN003___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100105  150.7948  364.5505  351.0650  424.7800   33.9409  105.8839
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.00_MONTAGEPLAT006___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100106  325.1624  377.5085 -424.1951 -325.7465   24.0000  137.9688
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.00_MONTAGEPLAT006___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100107  325.1624  377.5085  325.7465  424.1951   24.0000  137.9688
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_CRASHBOX_IN003___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100114  151.8158  354.1536 -413.4240 -333.8510   33.3936  111.0969
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.505.531.01_CRASHBOX_IN003___0_TRAEGER
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  88100115  151.8158  354.1536  333.8510  413.4240   33.3936  111.0969
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ANullschalen_Klebekontakt
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82000001  419.9385  610.8122 -811.1842  811.1842   24.2535  403.9682
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AAccel._Kuehler_Gehaeuse
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82000100  456.5012  565.1683 -754.9888  754.9888  400.6888  406.6708
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AAccel._Kuehler_Klebeflaechen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82000101  456.5149  565.1668 -754.9888  754.9888  400.6888  400.8027
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM1________000.0_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82003310  384.1629  600.7691 -853.7374 -493.7812   19.8617  408.3618
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.141.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014100  359.6349  383.3831 -509.7979 -490.9277  199.6920  226.8423
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.141.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014101  404.2264  578.1205 -868.5342 -471.3296   58.7176  369.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.141.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014102  345.5849  610.8052 -859.1811 -450.7173   25.8877  401.5549
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.141.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014103  593.9232  621.3608 -866.0867 -827.8456  149.9293  278.5085
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.141.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014104  561.0901  650.3833 -883.1289 -806.7769   25.6756  401.8075
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.142.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014200  404.2264  578.1205  471.3296  868.5342   58.7176  369.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.142.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014201  345.5849  610.8052  450.7173  859.1811   25.8877  401.5549
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.142.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014202  561.0901  650.3833  806.7769  883.1289   25.6756  401.8075
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.142.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014203  593.9232  621.3608  827.8456  866.0867  149.9293  278.5085
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.142.30-TM1________000.2_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014204  359.6349  383.3831  490.9277  509.7979  199.6920  226.8423
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.141.30-TM1________000.0_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82014232  594.6370  603.7484  833.7089  840.7209  242.9293  244.7707
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015523  440.2200  658.2209 -841.3525 -441.0371   18.8017  186.2228
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015525  425.6785  658.8104 -841.4296 -441.0371   23.5488  402.2391
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015527  440.2255  582.6516 -683.5043 -441.0372   19.0000   38.0441
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015529  476.6828  614.1923 -803.3190 -441.0372   25.4368   97.0061
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015530  431.3905  658.8104 -841.4296 -441.0372   19.0000   96.7557
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015539  486.5389  558.9363 -687.0410 -562.4933   31.5559   54.6898
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015540  502.4238  611.4156 -728.3571 -514.5671  106.5821  337.1530
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015550  531.2574  615.0070 -688.0282 -545.0873  131.4725  276.6034
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015623  440.2200  658.2209  441.2837  841.3525   18.8017  186.2228
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015625  425.6785  658.8104  441.2837  841.4296   23.5077  402.2391
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015627  440.2255  582.6516  441.2837  683.5043   19.0000   38.0441
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015629  476.6828  614.1923  441.2204  803.3190   25.4368   97.0061
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015630  431.3905  658.8104  441.0852  841.4296   19.0000   96.7557
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015639  486.5389  558.9363  562.4933  687.0410   31.5559   54.6898
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015640  502.4238  611.4156  514.5671  728.3571  106.5821  337.1530
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.165.30-TM1________001___0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82015650  531.2574  615.0070  545.0873  688.0282  131.4725  276.6034
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024300  417.6462  470.8148 -554.5065 -515.4676  403.5617  413.4735
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024302  551.1189  604.2875 -816.4627 -777.4238  403.5618  413.4736
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024303  551.1188  604.2875 -816.4627 -777.4238   14.3500   24.2618
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024304  417.6462  470.8148 -554.5065 -515.4676   14.3500   24.2618
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024305  551.1189  604.2875  777.4238  816.4627  403.5618  413.4736
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024306  417.6462  470.8148  515.4676  554.5065  403.5617  413.4735
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024307  417.6462  470.8148  515.4676  554.5065   14.3500   24.2618
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.243.30-TM1________000.0_0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82024308  551.1188  604.2875  777.4238  816.4627   14.3500   24.2618
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035110  569.4908  587.0744 -693.2930 -562.2310  346.6439  383.9299
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035115  610.5394  627.4949 -666.4800 -629.6472   35.1867   36.0593
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035117  590.9646  605.0329 -693.8365 -668.5540  256.0478  285.9701
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035118  596.0959  627.5311 -691.0482 -635.3677   34.9952  285.9470
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035119  555.7847  627.5927 -713.5190 -619.7989  285.9470  397.3681
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035120  460.2802  627.5362 -693.8020 -486.6855   34.8725  389.6457
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035121  549.1896  627.5934 -723.1877 -559.1658  285.9469  397.5340
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035122  489.2236  582.0464 -620.7624 -491.2939   59.3011  341.6754
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035123  454.7085  627.5939 -730.4393 -489.1911   34.8016  396.0232
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035124  507.8926  628.3260 -767.7446 -520.3836   35.0320  401.6052
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035125  429.6678  629.1631 -815.2271 -470.8842   34.7500  412.3477
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035126  448.6746  618.2595 -718.7482 -492.0895  274.2289  400.2002
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035127  496.7766  627.6000 -805.4387 -511.5718   34.7523  401.5709
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035128  443.1955  629.2827 -802.4712 -496.4009  278.0884  401.6679
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035129  564.3060  627.6000 -785.2609 -541.5464   34.7500  383.9299
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035130  438.4139  625.1314 -799.4896 -495.2603   39.2487  401.7650
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035131  570.2301  615.2147 -729.6416 -542.5959   34.7500  344.0609
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035132  589.4900  605.6797 -604.4622 -566.6191  318.1446  341.2134
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035133  567.0467  614.4941 -743.2380 -543.7573   34.7500  328.9145
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035135  571.8269  609.7152 -745.3718 -545.0327   35.0298  338.2915
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035136  567.6628  613.3255 -758.0711 -570.1188   35.0288  336.0510
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035137  587.7534  609.2650 -574.4014 -546.4230  305.3636  324.3975
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035138  607.1730  617.8992 -588.8255 -571.7916  323.1856  333.7697
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035139  595.4540  615.0468 -570.1741 -548.4711  306.1750  321.2602
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035140  603.0588  627.6000 -585.2653 -550.7317  306.4863  331.0295
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035210  569.4908  587.0744  562.2310  693.2930  346.6439  383.9299
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035215  610.5394  627.4949  629.6472  666.4800   35.1867   36.0593
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035217  590.9646  605.0329  668.5540  693.8365  256.0478  285.9701
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035218  596.0959  627.5311  635.3677  691.0482   34.9952  285.9470
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035219  555.7847  627.5927  619.7989  713.5190  285.9470  397.3681
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035220  460.2802  627.5362  486.6855  693.8020   34.8725  389.6457
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035221  549.1896  627.5934  559.1658  723.1877  285.9469  397.5340
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035222  489.2236  582.7327  491.2939  620.7624   59.3011  341.6754
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035223  454.7085  627.5939  489.1911  730.4393   34.8016  396.0232
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035224  507.8926  628.3260  520.3836  767.7446   35.0320  401.6052
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035225  429.6678  629.1631  470.8842  815.2271   34.7500  412.3477
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035226  448.6746  618.2595  492.0895  718.7483  274.2289  400.2002
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035227  496.7766  627.6000  510.9947  805.4387   34.7523  401.5709
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035228  443.1955  629.2827  496.4009  802.4712  278.0884  401.6679
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035229  564.3060  627.6000  541.5464  785.2609   34.7500  383.9299
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035230  438.4139  625.1314  495.2603  799.4896   39.2487  401.7650
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035231  570.2301  615.2147  542.5959  729.6416   34.7500  344.0609
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035232  589.4900  605.6797  566.6191  604.4622  318.1446  341.2134
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035233  567.0467  614.4941  543.7573  743.2380   34.7500  328.9145
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035235  571.4865  609.7152  545.0327  745.3718   35.0298  338.2915
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035236  567.5298  613.3255  570.1188  758.0711   35.0288  336.0510
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035237  587.7534  609.2650  546.4230  574.4014  305.3636  324.3975
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035238  607.1730  617.8992  571.7916  588.8255  323.1856  333.7697
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035239  595.4540  615.0468  548.4711  570.1741  306.1750  321.2602
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.351.30-TM1________001.0_0_Abluftfuehrung
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82035240  603.0588  627.6000  550.7317  585.2653  306.4863  331.0295
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.757.00-TM1________000.1_0_Halter_Vormontage
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82075700  600.3086  616.5832 -563.0206 -540.2327   75.7872  100.9036
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.757.00-TM1________000.1_0_Halter_Vormontage
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82075701  603.9348  614.8613 -552.9669 -533.4326   55.7890   87.2318
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.757.00-TM1________000.1_0_Halter_Vormontage
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82075800  600.3086  616.5832  540.1795  562.9271   75.8179  100.9071
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.757.00-TM1________000.1_0_Halter_Vormontage
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82075801  603.9348  614.8614  532.7875  552.9509   56.2972   87.2596
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.865.30-TM2________001.1_0_Kupplung_Hutchinson
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82086501  579.7371  604.2926 -870.2405 -855.3630  385.9500  403.0767
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.865.30-TM2________001.1_0_Kupplung_Hutchinson_NOT_IN_CONTACT
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82086503  576.8904  595.7672 -865.4244 -851.5774  384.5112  401.2793
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM1________000.0_0_Kuehler_NOT_IN_CONTACT
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103301  419.9385  567.6064 -811.1842  811.1842   24.2535  403.9682
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM1________000.0_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103308  396.6268  588.2168 -841.2206 -506.1156   25.9117  402.3118
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM9________000.0_0_Lufter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103324  494.8968  579.9415 -705.5720 -573.1730  145.5855  282.9578
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103337  538.8591  538.8597 -480.4000 -474.3000  363.6000  394.4000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103338  520.2590  557.4681 -523.7734 -502.2442  386.3798  394.4096
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103339  520.2590  557.4681 -512.0001 -482.1118  349.1669  394.4000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103340  525.8759  551.8619 -517.5029 -491.6357  349.1669  381.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103341  525.9642  551.7546 -514.7000 -480.4000  352.7976  394.4000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103342  612.8275  634.4586 -828.9827 -807.0048   13.3725   15.5578
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103343  609.4434  635.5428 -834.5401 -801.7232   13.9190   30.1805
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103344  609.4434  635.7161 -834.5401 -801.7232   27.7327   30.4432
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103345  607.2009  635.4627 -832.6239 -805.7485   13.3725   30.4432
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103352  501.6854  551.1085 -692.0577 -601.0518  163.1776  265.3365
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103353  501.6854  579.7088 -693.6406 -581.3074  157.6433  270.8615
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103354  539.8120  551.1085 -646.8378 -624.8749  202.0129  226.4925
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103355  534.8006  598.6561 -673.6031 -572.7330  160.5524  265.4860
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103356  525.1062  587.7952 -683.9272 -560.8925  135.7160  269.6067
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103357  546.9296  598.6561 -673.1756 -572.7330  159.2644  266.8241
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103358  542.9581  562.1649 -642.2270 -623.1472  206.5855  221.8855
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103359  548.4097  566.4547 -645.2889 -617.3013  197.7846  225.4585
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103360  541.5171  568.7473 -652.5986 -612.7106  191.6090  230.3236
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103361  529.2149  585.6592 -679.2944 -568.9564  145.8570  265.4825
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM1________000.0_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103408  396.6268  588.2168  506.1156  841.2206   25.9117  402.3118
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM1________000.0_0_Kuehler
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103409  384.1629  600.7691  493.7812  853.7374   19.8617  408.3618
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM9________000.0_0_Lufter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103424  494.8968  579.9415  573.1730  705.5720  145.5855  282.9578
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103437  538.8591  538.8597  474.3000  480.4000  363.6000  394.4000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103438  520.2590  557.4681  502.1107  523.7734  386.3798  394.4048
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103439  520.2590  557.4681  482.1118  512.0001  349.1669  394.4000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103440  525.8732  551.8619  491.6357  517.5029  349.1669  381.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103441  525.9642  551.7546  480.4000  514.7000  352.7976  394.4000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103442  612.8275  634.4586  807.0048  828.9827   13.3725   15.5578
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103443  609.4434  635.5428  801.7232  834.5401   13.9190   30.1805
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103444  609.4434  635.7161  801.7232  834.5401   27.7327   30.4432
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.106.033.30-TM2________000.0_0_Konsole
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103445  607.2009  635.4627  805.7485  832.6239   13.3725   30.4432
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103452  501.6854  551.1085  601.0518  692.0577  163.1776  265.3365
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103453  501.6854  579.7088  581.3074  693.6406  157.6433  270.8615
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103454  539.8120  551.1085  624.8749  646.8378  202.0129  226.4925
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103455  534.8006  598.6561  572.7442  673.6031  160.5600  265.4860
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103456  525.1062  587.7952  560.8925  683.9272  135.7160  269.6067
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103457  546.9091  598.6561  572.7442  673.1756  159.2145  266.8241
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103458  542.9581  562.1649  623.1472  642.2270  206.5855  221.8855
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103459  548.4097  566.4547  617.3013  645.2889  197.7846  225.4585
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103460  541.5171  568.7473  612.7106  652.5986  191.6090  230.3236
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM2___________000.0_0_Motor
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82103461  529.2149  585.6592  568.9564  679.2944  145.8570  265.4825
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.094.01-TM4________001.0_0_FLANSCH_KOND
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82309403  326.2587  351.1020  492.8130  522.9623  319.0279  360.6646
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.094.01-TM9________000.0_0_FLANSCH_KOND
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82309407  326.2390  351.1207 -523.0436 -492.8915  319.2669  361.4824
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9A1.573.097.05-TM5________000___0_FLAN_NW12M_P40496
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82309701  330.6369  351.0938  494.0712  523.4567   66.7481  109.0683
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.108.00-TM4________000___0_Flansch_NW10M
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82310806  330.6797  351.0165 -523.3453 -494.2742   66.7550  109.2456
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.02-TM1________000_      (>AB_AlZn4.5Mg1_T6_XX:24,  >SHELL_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311110  366.9226  540.1910 -841.0023 -521.6596   44.2799  388.0031
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311130  351.1749  368.4243 -518.3142  518.3142  196.9304  226.8674
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.02-TM1________000_      (>AB_AlZn4.5Mg1_T6_XX:24,  >SHELL_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311210  366.9226  540.1910  521.6596  841.0023   44.2799  388.0031
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311318  525.9103  544.5813  833.6921  852.7062   37.7443  389.3105
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311321  362.4296  381.2063  511.2718  530.8592   37.2500  388.3389
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311324  343.6206  367.0806  500.0982  525.0458  320.3558  357.5730
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311325  343.8059  366.6667  500.0975  524.7641   68.7088  107.0741
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311338  343.8060  366.6669 -524.7640 -500.0974   68.8846  107.2499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311339  343.8058  367.0810 -524.7641 -500.0975  320.7499  357.7499
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311340  362.5298  381.2063 -530.8592 -511.1347   37.2500  388.3389
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.111.05-TM_________000.2_0_Kondensator
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82311341  525.9103  544.5813 -852.7062 -833.6921   37.7443  389.3105
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AKuehler_Nullshell_Contact
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82370115  366.9226  588.2184 -841.2206 -506.1140   25.9117  402.3118
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AKuehler_Nullshell_Contact
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82370215  366.9226  588.2184  506.1140  841.2206   25.9117  402.3118
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.711.05-TM1________000.1_0_Dichtrahmen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82371125  353.6187  565.5877 -867.2554 -491.0089   25.8531  402.2062
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.573.711.05-TM1________000.1_0_Dichtrahmen
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82371126  353.6187  565.5877  491.0089  867.2554   25.8531  402.2062
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM3___________000.0_0_Stecker_links
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82445500  592.0430  630.4868 -546.5347 -505.6730  300.4095  343.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.959.455-TM3___________000.0_0_Stecker_links
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  82445601  592.4131  630.5106  505.8260  546.5887  300.4678  343.5527
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74500001
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74000001  966.1909 1103.5565 -817.1893  817.1711  139.5025  276.4706
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74500124
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74000124  785.6134 1291.4717 -817.9656 -676.7951  -50.9441  455.4174
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74500125
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74000125  800.3676 1274.9905 -826.7903 -808.1779  -32.8646  442.2554
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74500128
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74000128  799.3843 1275.6600 -841.0124 -817.1215  -33.2353  443.5402
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74500224
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74000224  785.6134 1291.4717  676.7951  817.9656  -50.9441  455.4174
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74500225
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74000225  800.3676 1274.9905  808.1779  826.7903  -32.8646  442.2554
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74500228
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74000228  799.3843 1275.6600  817.1215  841.0124  -33.2353  443.5402
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74516434
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74516434  712.0989 1364.8623 -898.7986 -639.0558 -115.5199  530.2921
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74516435
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74516435  696.2150 1379.7461 -877.1116 -657.0253 -118.2659  545.0626
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74516534
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74516534  712.0983 1364.9351  639.1307  898.8215 -115.5124  530.2930
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASectShll_74516535
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  74516535  696.2311 1379.7421  657.1171  877.1622 -118.2714  545.0629
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ANullschalen                         (>Klebeflaechen:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73000001 1084.1406 1138.8240 -716.5927  716.5927  139.3174  294.7185
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AAccel._Kuehler_Gehaeuse             (>PA66_GF30:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73000100 1159.0688 1165.0688 -689.9395  689.9395  112.4880  118.4880
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AAccel._Kuehler_Klebeflaechen        (>PA66_GF30:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73000101 1159.0688 1165.0688 -689.9395  689.9395  112.4880  118.4880
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.403.01-TM1_002_             (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73140301  862.9422 1212.6715 -817.2247 -743.4464   28.8609  378.9083
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.403.01-TM1_002_             (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73140401  862.9422 1212.6715  743.4464  817.2246   28.8609  378.9083
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.423.12-TM1_000_             (>AG_AlSi7Mg0.3-KT6L:24_00,  >SHE
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73142301 1110.6816 1235.9747 -842.5997 -677.1318   29.6209  353.8381
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.423.12-TM1_000_             (>AG_AlSi7Mg0.3-KT6L:24_00,  >SHE
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73142401 1110.6816 1235.9747  677.1318  842.5997   29.6209  353.8381
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.940.02-BET_002_Belagtr      (>SB_S420MC_QStE420TM_PL:24_00,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73194001 1121.7601 1214.5100 -800.8724 -729.2628   91.4441  289.1871
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.940.02-BEL_002_Belagma      (>SB_S420MC_QStE420TM_PL:24_00,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73194002 1129.0839 1214.0886 -796.3011 -734.2651   92.9417  280.9442
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.940.02-BET_002_Belagtr      (>SB_S420MC_QStE420TM_PL:24_00,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73194101 1121.7601 1214.5100  729.2628  800.8724   91.4441  289.1871
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.940.02-BEL_002_Belagma      (>SB_S420MC_QStE420TM_PL:24_00,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  73194102 1129.0839 1214.0886  734.2651  796.3011   92.9417  280.9442
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ANullschalen                         (>Klebeflaechen:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  70000001  753.6831 1154.3232 -603.4278  603.4278   25.9980  639.0126
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ABolzen_anschlag                     (>STAHL:EL3,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  70000015  757.1467  788.0392 -397.2753  397.2753    6.2500   16.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ASchrauben_ Blocklaenge_Kontakt      (>ODB.KONTAKT1:9,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  70000051 1245.5471 1364.4779 -403.2711  403.2711    7.2000   17.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AAccel._Fahrwerk_Klebeflaechen       (>PA66_GF30:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  70599991  854.0322 1200.0000 -398.0924  403.9207   18.6562   37.3554
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AAccel._Fahrwerk_Gehause             (>PA66_GF30:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  70599992  854.0000 1200.0000 -398.0924  404.0000   14.0000   37.3554
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07                      (>SB_ST52-3N_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71000821  900.5000  939.8000 -503.5000 -321.5000  117.2000  153.2000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07                      (>SB_ST52-3N_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71000822  900.4000  939.8000  322.0000  504.0000  117.2000  153.3000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07                      (>SB_ST52-3N_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71000823  870.4000  921.6000 -737.4000 -501.0000  132.0000  176.9000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07                      (>SB_ST52-3N_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71000824  870.1000  921.4000  501.5000  737.9000  132.1000  177.1000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105301  982.0000 1070.7001  434.1000  734.6000   50.4492   89.1513
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105302  982.1000 1070.8000 -734.6000 -434.1000   50.2490   89.0512
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105303  980.5000 1070.7001  382.1000  720.5000   25.8000   90.2513
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105304  980.6000 1070.9000 -720.5000 -382.1000   25.8000   90.1512
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105305  980.6000 1074.7001  387.7000  724.4000   31.2000   91.8513
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105306  980.8000 1074.6000 -724.3000 -387.7000   31.2000   91.7512
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105307  981.7000 1070.7001  615.1000  741.9000   50.7000   99.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.341.01_002_QUERLENKER_      (>AG_AlSi10Mg_T6_XX:187F14, >SHEL
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105308  981.9000 1070.9000 -741.9000 -615.2000   50.6000   98.8000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.053.01_005_Z_QUERLENKE      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105309  990.2000 1059.3000  595.8000  745.8000   46.9000  102.1000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.053.01_005_Z_QUERLENKE      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105310  990.3000 1059.4000 -745.7860 -595.8000   46.8000  102.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.053.01_005_Z_QUERLENKE      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105311 1019.1000 1076.7001  392.0000  434.0000   35.6000   74.7000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.053.01_005_Z_QUERLENKE      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105312 1018.2000 1077.5000  384.9000  441.1000   28.6000   81.8000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.053.01_005_Z_QUERLENKE      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105313 1019.1000 1076.7001 -434.0000 -392.0000   35.6000   74.7000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.053.01_005_Z_QUERLENKE      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105314 1018.3000 1077.5000 -441.1000 -384.9000   28.5000   81.7000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AQuerlenkerlager Prinzipabbildu      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105315  996.3000 1053.6000 -660.3000 -601.7000   48.2000   93.6000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AQuerlenkerlager Prinzipabbildu      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105316  998.6000 1034.3000 -741.0000 -692.5000   49.3000   99.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AQuerlenkerlager Prinzipabbildu      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105317  996.2000 1053.5000  601.8000  660.4000   48.3000   93.7000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AQuerlenkerlager Prinzipabbildu      (  >STAHL:1,  >SHELL_2,         t
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71105318  998.3000 1034.1000  692.5000  741.0000   49.4000   99.6000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114302  756.1700  793.9720 -403.2460 -364.6571   32.0771   56.4061
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114304  830.6762 1002.8806 -612.3311 -438.1016   35.1511   99.6270
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114306  957.4384 1030.6321 -639.5361 -564.6874   36.3372  103.5577
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114308  743.1959  978.5850 -586.0023 -351.8362   32.8624   65.2987
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114310  756.3492  906.8943 -515.2320 -366.0218   28.2823   63.7188
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114312 1006.4832 1042.9252 -651.7407 -611.2119   36.6037  105.2907
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114314  747.4753  941.7083 -549.3038 -356.0565   33.2692   61.2976
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114316  758.8318  923.9126 -531.7109 -367.2950   34.0693   59.3333
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114318  773.4034  966.7885 -574.8950 -382.1801   35.1610   89.0690
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ABuchse_LAENGSLENKER_li              (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114320  762.3185  787.8832 -396.7986 -371.4025   26.3464   59.9537
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ABuchse_LAENGSLENKER_li              (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114322  754.3665  795.0998 -405.0767 -362.7839   25.7042   60.6682
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ABuchse_LAENGSLENKER_re              (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114323  772.0000  778.0000  381.3065  387.3999   19.8885   68.8187
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ABuchse_LAENGSLENKER_li              (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114324  772.0000  778.0000 -387.3999 -381.3065   19.8885   68.8187
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114326  743.4288  835.3663 -443.4911 -352.4980   40.0257   49.4805
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114331  743.1959  775.5383 -385.1477 -351.8362   32.8624   49.5001
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114332  747.5447  759.5520 -369.1480 -356.2729   33.0864   47.9619
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114333  807.7432  835.6077 -444.5249 -415.3467   37.5080   59.9739
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114334  787.7905  821.7899 -430.6749 -396.0381   36.0770   57.2961
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114335  847.9270 1014.2611 -623.3148 -455.0379   35.0423  101.3501
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114336  853.3002 1025.6757 -634.6945 -460.3622   28.6747  103.2962
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114337  869.9279  972.9540 -580.9277 -476.8267   33.6048   93.5196
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114338  891.7224  918.9268 -527.3992 -498.4269   42.4094   73.0226
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114339  903.1680  930.3270 -538.8882 -509.7760   43.5189   74.9352
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114340  801.2916  846.3204 -455.2329 -409.1119   37.0963   62.0757
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114341  858.7798  982.5316 -591.4239 -465.7858   29.3721   98.8110
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114342  914.6345  948.9031 -556.9031 -521.2046   43.1491   79.5433
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114402  756.2570  794.0220  364.7220  403.2292   32.0771   56.4061
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114404  830.6762 1002.8806  438.1016  612.3311   35.1511   99.6270
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114406  957.4384 1030.6321  564.6874  639.5361   36.3372  103.5577
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114408  743.1959  978.5850  351.8362  586.0023   32.8624   65.2987
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114410  756.3506  906.8943  366.0218  515.2320   28.2823   63.7188
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114412 1006.4832 1042.9252  611.2119  651.7407   36.6037  105.2907
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114414  747.4753  941.7083  356.0565  549.3038   33.2692   61.2976
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114416  758.8318  923.9126  367.2950  531.7109   34.0693   59.3333
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114418  773.4034  966.7885  382.1801  574.8950   35.1610   89.0690
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ABuchse_LAENGSLENKER_re              (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114420  762.3185  787.8832  371.4025  396.7986   26.3464   59.9537
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ABuchse_LAENGSLENKER_re              (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114422  754.3665  795.0998  362.7839  405.0767   25.7042   60.6682
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114426  743.4288  835.3663  352.4980  443.4911   40.0257   49.4805
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114431  743.1959  775.5383  351.8362  385.1477   32.8624   49.5001
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114432  747.5447  759.5520  356.2729  369.1480   33.0864   47.9619
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114433  807.7432  835.6077  415.3467  444.5249   37.5080   59.9739
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114434  787.7905  821.7899  396.0381  430.6749   36.0770   57.2961
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114435  847.9270 1014.2611  455.0379  623.3148   35.0423  101.3501
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114436  853.3002 1025.6757  460.3622  634.6945   28.6747  103.2962
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114437  869.9279  972.9540  476.8267  580.9277   33.6048   93.5196
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114438  891.7224  918.9268  498.4269  527.3992   42.4094   73.0226
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114439  903.1680  930.3270  509.7760  538.8882   43.5189   74.9352
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114440  801.2916  846.3204  409.1119  455.2329   37.0963   62.0757
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114441  858.7798  982.5316  465.7858  591.4239   29.3721   98.8110
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.143.01-TM_003_LAENGSLE      (>AG_AlSi10Mg_T6_XX:124F9_VEETIL,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71114442  914.6345  948.9031  521.2046  556.9031   43.1491   79.5433
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.801.01-TM1_001__t=1.0m      (>AB_AW5754_AlMg3_A_MDB:24_00,  >
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71120101  857.2000 1132.2001 -747.2000 -730.2000   38.4000  363.3000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.351.801.01-TM1_001__t=1.0m      (>AB_AW5754_AlMg3_A_MDB:24_00,  >
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71120102  857.0000 1132.1000  730.4000  747.2000   38.5000  363.4000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.657.04-TM_002_Brembo-2      (>AGK_AC42100_AlSi7Mg0.3_T6_IWM:1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71165903  996.9000 1039.3035 -726.3000  726.3000   89.2000  109.8435
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.657.04-TM_002_Brembo-2      (>AGK_AC42100_AlSi7Mg0.3_T6_IWM:1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71165909  997.4123 1039.3035 -724.4485  724.4877   94.0652  109.8435
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.657.04-TM_002_Brembo-2      (>AGK_AC42100_AlSi7Mg0.3_T6_IWM:1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71166509  996.9000 1038.7001  687.8000  726.3000   89.4000  105.1000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.657.04-TM_002_Brembo-2      (>AGK_AC42100_AlSi7Mg0.3_T6_IWM:1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71166510  997.1000 1038.9000 -726.3000 -687.7000   89.2000  105.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.611.845-TM1___________000.0_0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71184520  991.7896 1130.3203 -691.7792 -563.9974  245.9300  360.1262
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A9P1.611.846-TM1___________000.0_0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71184620  991.7896 1130.3203  563.9974  691.7792  245.9300  360.1262
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.703.10-TM1________003___0_PDCC_STABI_VA
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71370100  836.2959 1172.5535 -516.7832  516.7832   35.0000  233.9243
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.703.10-TM1________003___0_PDCC_STABI_VA
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71370101  852.1000  893.9000 -291.0000  291.0000   29.5000   71.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.703.10-TM1________003___0_PDCC_STABI_VA
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71370105  858.1000  887.9000 -337.6000  337.6000   35.0000   64.9000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908301 1118.0579 1165.7688 -565.3745 -514.1315  118.9007  297.3019
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908302 1125.1957 1152.5229 -545.2239 -539.3828  434.1679  460.9937
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908303 1126.8733 1154.8936 -565.3217 -528.8868  271.4309  431.6656
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908304 1119.5859 1157.0294 -570.0209 -542.7159  427.3612  465.8814
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908305 1119.0021 1157.6301 -567.8740 -543.5497  427.0573  466.1702
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908306 1133.1937 1148.8228 -524.8248 -522.4922  322.4301  348.7919
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908307 1134.2056 1148.4879 -533.9773 -521.8451  312.7179  326.8130
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908308 1132.3676 1146.5514 -541.4874 -529.1533  404.2987  418.5164
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908309 1135.9668 1154.4379 -544.0211 -540.5314   85.6928  103.8716
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908310 1131.0138 1160.1576 -518.2676 -515.8416   82.1143  111.0979
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908311 1128.9816 1152.4769 -558.0060 -525.8303  125.9715  327.0678
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908312 1129.1071 1161.4838 -542.0072 -515.8416   79.1421  126.7776
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908401 1118.0579 1165.7688  514.1315  565.3745  118.9007  297.3019
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908402 1125.1957 1152.5229  539.3828  545.2239  434.1679  460.9937
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908403 1126.8733 1154.8936  528.8868  565.3217  271.4309  431.6656
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908404 1119.5859 1157.0294  542.7159  570.0209  427.3612  465.8814
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908405 1119.0021 1157.6301  543.5497  567.8740  427.0573  466.1702
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908406 1133.1937 1148.8228  522.4922  524.8248  322.4301  348.7919
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908407 1134.2056 1148.4879  521.8451  533.9773  312.7179  326.8130
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM1________002___0_Cylindrical_tube
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908408 1132.3676 1146.5514  529.1533  541.4874  404.2987  418.5164
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908409 1135.9668 1154.4379  540.5314  544.0211   85.6928  103.8716
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908410 1131.0138 1160.1576  515.8416  518.2676   82.1143  111.0979
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908411 1128.9816 1152.4769  525.8303  558.0060  125.9715  327.0678
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.083.03-TM2________001___0_Piston_rod
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71908412 1129.1071 1161.4838  515.8416  542.0072   79.1421  126.7776
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.291.01-TM_________000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71929115 1123.9387 1152.5096 -527.1254 -504.7761  308.6085  338.6655
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.291.01-TM_________000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  71929215 1123.9387 1152.5096  504.7761  527.1254  308.6085  338.6655
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.657.30_EM01-TM____002___0_RADTR_VA_LI_TOP_TM
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72165801 1019.0068 1088.7913 -669.4352 -586.8309  265.0204  376.0444
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.341.658.30_EM01-TM____002___0_RADTR_VA_RE_TOP_TM
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72165901 1019.0068 1088.7913  586.8309  669.4352  265.0204  376.0444
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.015.02_001_Z Stuetzlag      (>AGD_AlSi9MgMn_Silafont-36_T6_ix
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72301901 1067.1000 1140.4000  495.2000  569.9000  606.1000  654.6000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.015.02_001_Z Stuetzlag      (>AGD_AlSi9MgMn_Silafont-36_T6_ix
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72301902 1067.1000 1140.3000 -570.0000 -495.2000  606.1000  654.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.015.02_001_Z Stuetzlag      (>AGD_AlSi9MgMn_Silafont-36_T6_ix
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72301903 1033.1000 1170.4000  469.8000  603.0000  594.1000  639.6000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.015.02_001_Z Stuetzlag      (>AGD_AlSi9MgMn_Silafont-36_T6_ix
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72301904 1030.7001 1170.4000 -607.3000 -469.9000  581.6000  639.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.015.02_001_Z Stuetzlag      (>AGD_AlSi9MgMn_Silafont-36_T6_ix
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72301905 1030.7001 1170.4000  469.8000  607.3000  581.6000  639.6000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.015.02_001_Z Stuetzlag      (>AGD_AlSi9MgMn_Silafont-36_T6_ix
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72301906 1033.1000 1170.4000 -603.0000 -469.9000  594.2000  639.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AHDBT3X_991.343.041.A0_EM03-TM1      (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304501 1017.4000 1114.0000 -674.9000 -538.0000  229.2000  544.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AHDBT3X_991.343.041.A0_EM03-TM1      (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304502 1017.0000 1113.8000  538.1000  675.2000  229.4000  544.6000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AHDBT3X_991.343.041.A0_EM03-TM1      (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304503 1020.2000 1090.9000 -669.6000 -552.2000  246.8000  391.6000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AHDBT3X_991.343.041.A0_EM03-TM1      (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304504 1019.8000 1090.6000  552.4000  669.9000  247.0000  391.8000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AHDBT3X_991.343.041.A0_EM03-TM4      (>SB_HX420LAD+Z_MDB:24SR_00,  >SH
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304505 1038.1000 1114.1000  550.4000  621.4000  437.4000  481.0000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AHDBT3X_991.343.041.A0_EM03-TM4      (>SB_HX420LAD+Z_MDB:24SR_00,  >SH
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304506 1038.3000 1114.4000 -621.2000 -550.2000  437.4000  480.9000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.511.01-TM1_003__FEDERA      (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304509 1044.2001 1153.2001  488.4000  595.5000  580.9000  625.7000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.511.01-TM1_003__FEDERA      (>SB_ST37-2_XX:24SR,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72304510 1044.2001 1153.2001 -595.5000 -488.4000  580.9000  625.5000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.531.10-TM1_002__SCHRAU      (>MG_AM50_XX:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72353101 1037.7001 1148.1000  494.7000  620.7000  439.8000  618.2000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.531.10-TM1_002__SCHRAU      (>MG_AM50_XX:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72353102 1037.9000 1148.1000 -620.5000 -494.7000  439.7000  618.1000
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.815.00-TM1________000.1_0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72881520 1008.7190 1088.6614 -468.9932 -445.0000  280.4123  376.9980
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.816.00_EM01-TM1___000.0_0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72881620 1008.7211 1088.7188  445.0000  468.9009  280.4116  376.9156
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.817.00_TM_________000.1_0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72881825 1025.4448 1080.9152 -465.0000 -456.7500  356.8726  372.9719
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.343.817.00_TM_________000.1_0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72881925 1025.4325 1080.8970  456.6427  464.8927  356.7577  372.8570
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A900.175.020.03-TM1________000___0_Hohlschraube_M12x1.5
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72902025 1131.8883 1148.6461 -541.4874 -505.8792  405.6046  421.6257
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A900.175.020.03-TM1________000___0_Hohlschraube_M12x1.5
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72902125 1131.8883 1148.6461  505.8792  541.4874  405.6046  421.6257
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.257.03_HALTEBLECH_000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925701 1098.3877 1162.3021 -531.9605 -510.4470  308.6196  351.7612
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.257.03_LINE2_TM1__000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925703 1065.8431 1164.3633 -534.6926 -513.8188  299.5674  396.1580
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.257.03_SCHLAUCH_TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925704  876.9714 1081.6650 -539.0763 -466.4784  320.7115  413.6320
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.257.03_SCHLAUCH_TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925705  865.7436 1097.6038 -539.0763 -459.7329  303.3333  349.3690
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AADAPTER_D8-TM1____________000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925717  860.3486  892.1766 -480.5801 -457.2690  294.3065  336.3274
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APRESSHUELSE_520-5108-TM1__000___0_Hochdruck-D16.4_d8.1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925723 1063.3297 1100.2388 -540.8422 -519.4414  318.3072  355.1255
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APRESSHUELSE_ADAPTER-TM1___000___0_Hochdruck-D16.4_d8.1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925724  863.5142  899.6662 -489.3394 -457.0604  301.1804  341.7730
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.257.03_HALTEBLECH_000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925801 1098.3877 1162.3021  510.4470  531.9605  308.6196  351.7612
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.257.03_LINE2_TM1__000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925803 1065.8431 1164.3633  513.8188  534.6926  299.5674  396.1580
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.257.03_SCHLAUCH_TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925805 1069.1227 1097.6038  521.1138  539.0763  320.8088  349.3690
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APRESSHUELSE_520-5108-TM1__000___0_Hochdruck-D16.4_d8.1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925823 1063.3297 1100.2388  519.4414  540.8422  318.3072  355.1255
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.259.03_LINE3_TM1__000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925902 1084.1473 1130.8971 -519.6434 -507.8524  331.3046  377.2083
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.259.03_SCHLAUCH-TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925903  850.3089 1098.5781 -523.8576 -466.4042  338.7333  445.5641
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.259.03_SCHLAUCH-TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925904  839.3408 1115.2050 -523.7152 -460.4889  320.9510  375.3908
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
AADAPTER_D8-TM1____________000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925917  833.8694  865.8486 -480.5690 -457.2691  312.2747  354.4062
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APRESSHUELSE_520-5108-TM1__000___0_Hochdruck-D16.4_d8.1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925923 1080.3380 1117.5889 -525.4438 -504.4257  344.3462  381.1176
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APRESSHUELSE_ADAPTER-TM1___000___0_Hochdruck-D16.4_d8.1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72925924  837.0351  873.2454 -489.3737 -457.0604  319.1486  359.8365
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.259.03_LINE3_TM1__000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72926002 1084.1473 1130.8971  507.8524  519.6434  331.3046  377.2083
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.259.03_SCHLAUCH-TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72926004 1086.1237 1115.2050  506.1326  523.7152  346.4704  375.3908
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
APRESSHUELSE_520-5108-TM1__000___0_Hochdruck-D16.4_d8.1
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72926023 1080.3380 1117.5889  504.4257  525.4438  344.3462  381.1176
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ARINGSTUTZEN_B8_DIN_7642-TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72926025 1126.7112 1149.8340 -525.9310 -503.5107  312.3767  421.2632
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ARINGSTUTZEN_B8_DIN_7642-TM000___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72926125 1126.7112 1149.8340  503.5107  525.9310  312.3767  421.2632
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.275.03-TM1________000___0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72927520  853.3518  899.6766 -461.2292 -446.9993  316.3228  354.7812
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.275.03-TM1________000___0_Halter_not_in_contact
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72927521  847.2458  867.6287 -456.5933 -446.9993  330.4900  359.9337
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.277.02-TM1________001___0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72927720  832.2725  899.8474 -489.8900 -452.3783  298.6992  358.1285
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.277.02-TM1________001___0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72927723  855.2616  866.8412 -482.7523 -452.3784  312.6820  327.9892
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.277.02-TM1________001___0_Halter
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72927724  863.6683  876.4784 -488.4846 -458.6234  326.8532  341.0965
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.281.02-TM1________000___0_Daempfungsgummi
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72928120  832.2725  899.8474 -489.8900 -452.3783  298.6992  358.1285
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.359.00-TM1________004___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72935925 1133.9598 1149.4857 -533.9773 -498.5298  313.0466  330.0431
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.359.359.00-TM1________004___0_
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  72936025 1133.9598 1149.4857  498.5298  533.9773  313.0466  330.0431
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
ANullschale_Klebekontakt             (>Klebeflaechen:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  80000001  898.7028  924.7896 -231.9270  231.9277   63.4157   71.8919
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07-TM1_000_LENKGET      (>AG_AlSi9Cu3_AC-46200:24_00,  >S
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  80700502  810.0508 1028.6387 -260.8465  272.0000   65.7143  215.3991
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07-TM1_000_LENKGET      (>AG_AlSi9Cu3_AC-46200:24_00,  >S
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  80700503  899.1219  949.8964 -220.4000  129.3100  105.6671  157.2636
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07-TM1_000_LENKGET      (>AG_AlSi9Cu3_AC-46200:24_00,  >S
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  80700504  808.9525  995.5111 -234.1715  124.6866   71.0982  174.1804
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07-TM1_000_LENKGET      (>MG_MgAl5.5_XX:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  80700505  811.9809 1028.6387 -274.0000  203.8066   67.0289  215.3991
$--------1---------2---------3---------4---------5---------6---------7---------8
*DEFINE_BOX_TITLE
A991.347.005.07-TM1_000_LENKGET      (>fake_steel:24,  >SHELL_2,
$    BOXID      XMIN      XMAX      YMIN      YMAX      ZMIN      ZMAX
  80700506  982.6810 1028.6605 -250.0579 -200.9467  163.0467  208.8403
$--------1---------2---------3---------4---------5---------6---------7---------8
*END
